version: '3.7'

services:
  web:
    build: .
    ports:
      - 1234:1234

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/foo

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db-data:
